"use client";
import { useState } from "react";
export function TamperSample() {
  const [mask,setMask]=useState(true);
  const [image,setImage]=useState<string | null>(null);
  const [fileName,setFileName]=useState("SAMPLE / ARCHIVE 001");
  const loadImage=(file:File | undefined)=>{ if(!file)return; setImage(URL.createObjectURL(file)); setFileName(file.name.toUpperCase()); setMask(true); };
  return <div className="lab-workbench"><div className="workbench-bar"><span>DOCUMENT VIEWER / {fileName}</span><span>{image?'LOCAL PREVIEW · NO UPLOAD':'PRELOADED SAMPLE · NO INFERENCE'}</span></div><div className="workbench-body"><div className="lab-document-stage">{image?<div className="uploaded-document"><img src={image} alt="Your locally selected document preview"/>{mask&&<span className="uploaded-overlay">ILLUSTRATIVE REGION</span>}</div>:<div className="lab-document"><div className="document-letterhead">TAFE / SAMPLE ARCHIVE<span>001</span></div><h3>Document integrity<br/>inspection record</h3><p>Prepared for the document forensics workbench.</p><hr/><div className="document-rows"><div><span>Reference</span><b>TF–2026–001</b></div><div><span>Document</span><b>Illustrative sample</b></div><div className={mask?'example-region visible':'example-region'}><span>Amount</span><b>12,480.00</b>{mask&&<small>ILLUSTRATED REGION</small>}</div><div><span>Review</span><b>Visual inspection</b></div></div><p className="document-copy">A localized mask helps a reviewer identify a region to inspect. The highlighted amount is a designed example, not a prediction made by the model.</p><div className="document-stamp">SAMPLE<br/>NOT A REAL RECORD</div></div>}</div><div className="lab-view-controls"><p className="lab-kicker">VIEW MODE / {mask?'OVERLAY':'DOCUMENT'}</p><h3>{image?'Preview your document.':'A small region.'}<br/>{image?'Keep your file private.':'A closer inspection.'}</h3><p>{image?'Your image is rendered in this browser only. This public page does not send it to a server or claim a model prediction.':'Switch the overlay on and off to see how a localized result is presented. The highlight is fixed for this illustration.'}</p><div className="demo-actions"><label className="lab-button upload-button">Choose an image<span>＋</span><input type="file" accept="image/*" onChange={e=>loadImage(e.target.files?.[0])}/></label><button type="button" className="lab-button" aria-pressed={mask} onClick={()=>setMask(!mask)}>{mask?'Hide example overlay':'Show example overlay'}<span>{mask?'−':'+'}</span></button></div><div className="viewer-key"><i/> ILLUSTRATED INSPECTION REGION</div><p className="lab-footnote">The GPU checkpoint runs in the verified Colab package. This page is a privacy-safe interface demo; the overlay is illustrative.</p></div></div></div>;
}
