"use client";
import Link from "next/link";
import { useState } from "react";
import { classes, models, nav } from "./data";

export function Header(){return <header className="header"><Link className="brand" href="/"><span className="brandmark">ID</span><span>IDSentinel</span></Link><nav>{nav.map(([href,label])=><Link key={href} href={href}>{label}</Link>)}</nav><details className="mobile-nav"><summary>Menu</summary><div>{nav.map(([href,label])=><Link key={href} href={href}>{label}</Link>)}</div></details><a className="git" href="https://github.com/ninadnaik03/idsentinel">GitHub ↗</a></header>}
export function Footer(){return <footer><div><b>IDSentinel</b><p>Independent, paper-inspired research implementation.</p></div><div className="footer-links"><Link href="/methodology">Methodology</Link><Link href="/about">Limitations</Link><a href="https://github.com/ninadnaik03/idsentinel">Source</a></div><span>Experimental · Not production ready</span></footer>}
export function Shell({children}:{children:React.ReactNode}){return <><Header/><main>{children}</main><Footer/></>}
export function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow">{children}</p>}
export function PageHero({kicker,title,copy}:{kicker:string,title:string,copy:string}){return <section className="page-hero"><Eyebrow>{kicker}</Eyebrow><h1>{title}</h1><p className="lede">{copy}</p></section>}
export function Bars({field="macro"}:{field?:"macro"|"accuracy"}){return <div className="bars" role="img" aria-label={`${field} comparison`}>{models.map(m=>{const v=m[field];return <div className="bar-row" key={m.id}><span>{m.id}</span><div><i style={{width:`${v*100}%`}} className={m.accent}/></div><strong>{v.toFixed(3)}</strong></div>})}</div>}
export function ClassBars(){return <div className="class-bars">{classes.map((c,i)=><div key={c}><h4>{c}</h4>{models.map(m=><div className="mini" key={m.id}><span>{m.id}</span><i style={{width:`${m.classF1[i]*100}%`}}/><b>{m.classF1[i].toFixed(3)}</b></div>)}</div>)}</div>}
export function Matrix({matrix}:{matrix:number[][]}){return <div className="matrix" aria-label="Confusion matrix">{matrix.flatMap((row,r)=>row.map((v,c)=><span key={`${r}-${c}`} style={{"--heat":v/12} as React.CSSProperties}>{v}</span>))}</div>}
export function ExperimentExplorer(){const [active,setActive]=useState(1);const m=models[active];return <div className="explorer"><div className="tabs" role="tablist">{models.map((x,i)=><button className={i===active?"active":""} onClick={()=>setActive(i)} key={x.id}>{x.id} <span>{x.name}</span></button>)}</div><div className="experiment-panel"><div><Eyebrow>{m.id} · Frozen test split</Eyebrow><h2>{m.name}</h2><div className="metric-grid"><div><small>Accuracy</small><strong>{(m.accuracy*100).toFixed(2)}%</strong></div><div><small>Macro-F1</small><strong>{m.macro.toFixed(3)}</strong></div><div><small>Parameters</small><strong>{m.params}</strong></div><div><small>Failures</small><strong>{m.failures}/44</strong></div></div>{m.weights&&<p className="note">Learned fusion weights: {m.weights}. Not causal feature-importance estimates.</p>}</div><div><Matrix matrix={m.matrix}/><p className="axis">Rows: true · Columns: predicted</p></div></div><div className="artifact-pair"><img src={`/research/${m.id.toLowerCase()}-training.png`} alt={`${m.id} real training curves`}/>{m.id!=="M3"&&<img src={`/research/${m.id.toLowerCase()}-weights.png`} alt={`${m.id} learned fusion weights`}/>}</div></div>}
export function DemoBox(){const [file,setFile]=useState<string>();return <div className="demo-shell"><label className="drop"><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)setFile(URL.createObjectURL(f))}}/><span className="upload-icon">＋</span><h3>{file?"Document ready":"Drop an identity-document image"}</h3><p>{file?"Preview remains on this device.":"or choose a file to preview the analysis interface"}</p></label>{file?<div className="preview"><img src={file} alt="Locally selected document preview"/><div><Eyebrow>Inference unavailable</Eyebrow><h2>No prediction was generated</h2><p>This public build intentionally does not fake live inference. The interface is ready for a future checkpoint-backed API.</p><button disabled>Run analysis · backend not connected</button></div></div>:<Recorded/>}</div>}
function Recorded(){return <div className="recorded"><div><Eyebrow>Recorded experiment example</Eyebrow><h2>How results will appear</h2><p>This is a UI contract using aggregate, verified M4 test metrics—not a prediction for an uploaded image.</p></div>{classes.map((c,i)=><div className="confidence" key={c}><span>{c}</span><i style={{width:[48,89,67][i]+"%"}}/><b>{[.480,.889,.667][i].toFixed(3)} F1</b></div>)}</div>}
export function ArchitectureDiagram(){return <div className="architecture-diagram"><div className="input-node">384×384 RGB<br/><small>portrait + context crop</small></div><div className="branch semantic"><b>Semantic</b><span>ConvNeXt-Tiny</span><small>high-level representation</small></div><div className="branch texture"><b>Texture</b><span>32×32 → 16→32→64</span><small>64-D representation</small></div><div className="branch edge"><b>Edge</b><span>Luminance → Sobel X/Y</span><small>32-D representation</small></div><div className="output-node">Tested as two-branch systems<br/><small>M4: Semantic + Texture · M5: Semantic + Edge</small></div></div>}
