import Link from "next/link";
import { ArchitectureDiagram, Bars, ClassBars, Eyebrow, PaperModal, Shell } from "./components";
import { models } from "./data";

const workflow = [
  ["M0", "Audit the paper", "Separated paper-described components from assumptions before implementation."],
  ["M1", "Protect scientific validity", "Audited provenance, licensing, lineage, source confounding, and leakage risks."],
  ["M2", "Build the protocol", "Created a deterministic, group-safe 300-sample DLC-2021 reduced benchmark."],
  ["M3", "Establish semantics", "Trained the frozen-split ConvNeXt-Tiny baseline."],
  ["M4", "Isolate texture", "Added a lightweight pixel-only texture branch and learned fusion."],
  ["M5", "Isolate edges", "Added fixed Sobel gradients and a lightweight learned edge branch."],
];

export default function Home(){return <Shell>
  <section className="hyperverge-note"><div><Eyebrow>A note to the team that inspired this sprint</Eyebrow><h2>Hello HyperVerge team!</h2><p>I recently interviewed for the Deep Learning Research Intern role. After the interview, I spent time exploring HyperVerge&apos;s Identity Verification, Document Verification, Forgery Check, Face Authentication, and fraud/deepfake-detection products—and the computer-vision question behind them: how can a system determine whether an identity presented to it is actually trustworthy?</p><p>That led me down a research rabbit hole around document presentation attacks, where genuine IDs can be presented through prints, screens, or manipulated representations. I eventually found the paper <cite>“Multi-Branch Forensic Architecture for ID Card Presentation Attack Detection with Portrait Extraction.”</cite></p><div className="paper-line"><strong>Marko Peterlin &amp; Borut Batagelj · ERK 2025</strong><PaperModal/></div><p>Instead of only waiting for my interview result, I gave myself 24 hours to implement, test, and critically evaluate the idea from scratch. That became IDSentinel. This website is the complete build story—what worked, what failed, the dataset issues I found, and what I learned.</p></div></section>
  <section className="hero"><div><Eyebrow>Implemented in 24 hours · Protocol A-Reduced</Eyebrow><h1>Semantic.<br/><span>Texture. Edge.</span></h1><p className="lede">IDSentinel is my independent, paper-inspired implementation of a forensic vision system for distinguishing bona fide identity-document captures from print and screen presentation attacks.</p><div className="actions"><Link className="primary" href="/24-hours">Read the build story</Link><Link className="secondary" href="/experiments">Explore experiments</Link></div><p className="hero-disclaimer">Research prototype · no production or state-of-the-art claim</p></div><div className="hero-orbit"><span className="orb semantic">SEM</span><span className="orb texture">TXT</span><span className="orb edge">EDG</span><div className="scan-card"><small>BEST OBSERVED</small><strong>0.679</strong><span>Macro-F1 · reduced protocol</span></div></div></section>
  <section className="stat-strip">{[["300","balanced samples"],["3","classes"],["3","evaluated models"],["44","frozen test samples"]].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</section>

  <section className="section"><Eyebrow>The complete project</Eyebrow><div className="split"><h2>Can complementary forensic evidence improve over semantics alone?</h2><div><p>Presentation attacks place a reproduction between the camera and the identity document. A printed copy can preserve semantic content while changing surface texture. A screen recapture can preserve layout while adding display structure and edge characteristics.</p><p>The project therefore tests three controlled configurations: semantic ConvNeXt alone, semantic plus texture, and semantic plus fixed-Sobel edge evidence. The classifier receives pixels only—never device, source, detector, file-path, or padding metadata.</p></div></div><div className="attack-grid">{[["BONA FIDE","Real identity-document capture","01"],["PRINT","Printed reproduction presented to the camera","02"],["SCREEN","Document recaptured through another display","03"]].map(x=><article key={x[0]}><small>{x[2]}</small><h3>{x[0]}</h3><p>{x[1]}</p><div className={`attack ${x[0].toLowerCase().replace(" ","-")}`}/></article>)}</div></section>

  <section className="section panel"><Eyebrow>Architecture</Eyebrow><div className="split"><h2>One audited crop. Complementary representations.</h2><p>Every model receives the same 384×384 RGB portrait/context crop. The semantic backbone captures higher-level appearance; the texture path measures learned pixel structure; the edge path exposes fixed luminance gradients before lightweight learned processing.</p></div><ArchitectureDiagram/><Link className="text-link" href="/architecture">Inspect every layer and freeze decision →</Link></section>

  <section className="section forensic-showcase"><div className="split"><div><Eyebrow>Inside the edge representation</Eyebrow><h2>Original → grayscale → Sobel magnitude.</h2></div><p>This real M5 research artifact shows deterministic examples across BONA_FIDE, PRINT, and SCREEN, including both correct and failed predictions. The fixed Sobel front end reveals contour structure without pretending it is an attention map or causal explanation.</p></div><figure><img src="/research/m5-forensic-grid.png" alt="M5 forensic grid comparing original identity-document crops, grayscale conversions, and Sobel magnitude maps for correct and failed examples across three classes"/><figcaption>Recorded experiment visualization · M5 fixed-Sobel edge branch · examples selected deterministically by manifest order</figcaption></figure></section>

  <section className="section"><Eyebrow>Dataset and scientific controls</Eyebrow><div className="split"><div><h2>Protocol design came before training.</h2><p>A proposed four-class DLC-2021 + SIDTD merge was blocked because dataset source could reveal the composite label. Instead, the primary experiment uses DLC-2021 alone for BONA_FIDE, PRINT, and SCREEN.</p><Link className="text-link" href="/methodology">Read the methodology →</Link></div><div className="control-list"><div><b>214 / 42 / 44</b><span>train / validation / test</span></div><div><b>0</b><span>base-document split violations</span></div><div><b>0</b><span>exact or pHash-distance-6 cross-split clusters</span></div><div><b>300 / 300</b><span>successful portrait/context crops</span></div></div></div><p className="research-callout">Protocol A-Reduced is not the full DLC-2021 benchmark. It is a controlled 24-hour reduced reproduction protocol built under dataset-access, network, storage, and 8 GB laptop constraints.</p></section>

  <section className="section"><div className="split"><div><Eyebrow>Frozen test results</Eyebrow><h2>Texture produced the highest observed score.</h2><p>M4 reached 0.679 Macro-F1, driven primarily by observed PRINT improvement. Edge also improved over the semantic baseline overall, but SCREEN F1 decreased in that run.</p><p>With 44 test samples and one primary seed, these differences are descriptive—not evidence of statistical superiority.</p></div><Bars/></div><ClassBars/><div className="model-cards">{models.map(m=><article key={m.id}><span>{m.id}</span><h3>{m.name}</h3><strong>{m.macro.toFixed(3)}</strong><small>Macro-F1</small><p>{m.failures} failures / 44</p></article>)}</div><Link className="text-link" href="/experiments">Open metrics, confusion matrices, and training curves →</Link></section>

  <section className="section panel"><Eyebrow>Structured implementation</Eyebrow><h2>Six research gates, not one training script.</h2><div className="workflow-grid">{workflow.map(([id,title,copy])=><article key={id}><span>{id}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><Link className="primary" href="/24-hours">See how I built it in 24 hours</Link></section>

  <section className="section"><Eyebrow>Failure analysis</Eyebrow><div className="split"><div><h2>Branches changed which samples failed.</h2><p>Of M3&apos;s 18 failures, seven were corrected by both branch models, four only by texture, two only by edge, and five persisted across all configurations. BONA_FIDE remained the hardest class.</p></div><div className="transition-grid"><div><strong>7</strong><span>corrected by both</span></div><div><strong>4</strong><span>texture only</span></div><div><strong>2</strong><span>edge only</span></div><div><strong>5</strong><span>persistent</span></div></div></div><Link className="text-link" href="/failures">Study the failure transitions →</Link></section>

  <section className="section cta"><Eyebrow>Research-grade by being honest</Eyebrow><h2>The limitations stay visible.</h2><p>Only 300 samples, 44 test cases, one seed, no stochastic augmentation, unequal lineage coverage, a possible padding shortcut, and architecture changes that prevent a perfectly head-matched causal ablation.</p><div className="actions centered"><Link className="primary" href="/about">About this implementation</Link><a className="secondary" href="https://github.com/ninadnaik03/idsentinel">View source on GitHub ↗</a></div></section>
</Shell>}
